baseURL = "https://daryna-smyrnova.github.io/"
languageCode = "en-us"
title = "Eddie Webb"
theme = "hugo-resume"

[params]
    firstName = "Daryna"
    lastName = "Smyrnova"
    address = "Bruxelles, Belgium"
    phone = "+32 478 120383"
    contactNote = "Computational Chemistry"
    profileImage = "img/twitter.jpg"
    email = "daryna.smyrnova@gmail.com"
    description = "Scientific challenges are my passion. My experience comes from interdisciplinary projects involving fields of computational chemistry, physics and biology. Finding the right computational tools, be it molecular dynamics, quantum chemistry or problem tailored data analysis, to provide a working model explaining experimental evidences is what I do on a daily basis. Designing, developing and executing my own projects, as part of a bigger international collaboration, makes me a real team player. Python & Linux are my favourite tools, but I am always eager to learn more. And my diverse educational background has equipped me with the right quick learning skills."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = false
    showEducation = false

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/daryna-smyrnova/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/daryna-smyrnova"


#[params.google.analytics]
#    trackerID = "XX-123446-01"
